language: python
install:
  - pip install tox
dist: xenial
python: 3.6  # Use the oldest supported version of python as default.
script:
    - tox -e $TOX_ENV
matrix:
  include:
    # UNIT TESTS
    # On most recent versions of python.
    - python: 3.6
      env: TOX_ENV=py36
      after_success:
        # Correct coverage xml for coverage services.
        - pip install codecov
        - >
          bash -c 'set -eux;
          pkg_path=$(find .tox/py*/lib/python*/site-packages/array_as_vcf -maxdepth 0 -type d);
          sed -i "s:${pkg_path}:src/array_as_vcf:g" coverage.xml'
        - codecov -v  # -v to make sure coverage upload works.
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
